config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "records#index"
  resources :records do
   resources :comments, only: [:create, :destroy]
   resource :likes, only: [:create, :destroy]
   collection do
    get 'search'
   end
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '未就学児' },
    { id: 3, name: '小学１年生' },
    { id: 4, name: '小学２年生' },
    { id: 5, name: '小学３年生' },
    { id: 6, name: '小学４年生' },
    { id: 7, name: '小学５年生' },
    { id: 8, name: '小学６年生' },
    { id: 9, name: '中学１年生' },
    { id: 10, name: '中学２年生' },
    { id: 11, name: '中学３年生' },
    { id: 12, name: '高校１年生' },
    { id: 13, name: '高校２年生' },
    { id: 14, name: '高校３年生' },
    { id: 15, name: '大学生' },
    { id: 16, name: '社会人' },
    { id: 17, name: 'その他' }
    ]
    

  include ActiveHash::Associations
  has_many :records

  end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :record

  validates :text, presence: true
end

app/models/evaluation.rb
class Evaluation < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '大変満足' },
    { id: 3, name: '満足' },
    { id: 4, name: '普通' },
    { id: 5, name: '良くなかった' },
    { id: 6, name: '大変良くなかった' }
    ]

  include ActiveHash::Associations
  has_many :records

  end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :record
  
  validates :user_id, uniqueness: { scope: :record_id}
  # validates :user_id,uniqueness: true
  # validates :record_id,uniqueness: true
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :evaluation

  with_options presence: true do
    validates :tr_content
    validates :tr_theme
    validates :image
    validates :event
    validates :tr_day
    validates :mvp
    validates :mvp_reason
  end
  
  with_options presence: true,numericality: { other_than: 1 }  do 
    validates :category_id 
    validates :evaluation_id
  end


  def self.search(search)
    if search != ""
      Record.where('event LIKE(?)', "%#{search}%")
    else
      Record.all
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :records
         has_many :comments
         has_many :likes

         validates :email, presence: true,uniqueness: true

         with_options presence: true do
          validates :nickname
          validates :birth_day
         end

         validates :password, presence: true,length: { minimum: 6 }, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i }

         with_options presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々]+\z/ } do
          validates :family_name
          validates :first_name
         end

         with_options presence: true, format: { with: /\A[ァ-ヶー－]+\z/ } do 
          validates :family_name_kana
          validates :first_name_kana
         end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :family_name, :first_name, :family_name_kana, :first_name_kana, :birth_day])
  end

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  

    def create
      @comment = Comment.new(comment_params)
      if @comment.save
        redirect_to record_path(@comment.record)
      else
        @record = @comment.record
        @comments = @record.comments
         render "records/show" 
      end
    end
  
    def destroy
      @record = Record.find(params[:record_id])
      comment = @record.comments.find(params[:id])
      if current_user.id == comment.user.id
        comment.destroy
      redirect_back(fallback_location: root_path)
      else
        render "records/show"
      end
    end

    private
    def comment_params
      params.require(:comment).permit(:text).merge(user_id: current_user.id, record_id: params[:record_id]) 
    end

    
end
  

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    # @record = Record.find(params[:record_id])
    like = current_user.likes.build(record_id: params[:record_id])
    if like.save
     redirect_back(fallback_location: root_path)
    else
      @record = like.record
      like = @record.likes
      redirect_back(fallback_location: root_path)
    end
  end
  
  def destroy
    user=current_user
    record=Record.find(params[:record_id])
    if like=Like.find_by(user_id: user.id,record_id:record.id)
     like.destroy
     redirect_back(fallback_location: root_path)
    else
     redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:edit, :show, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]

  def index
    @records = Record.includes(:user).order("created_at DESC")
    @records = Record.page(params[:page]).per(4).order("created_at DESC")
  end

  def new
    @record = Record.new
  end

  def create
    @record = Record.new(record_params)
    if @record.save
      redirect_to root_path
    else
      render :new
   end
  end

  def show
    @comment = Comment.new
    @comments = @record.comments.includes(:user)
    # @like = Like.new
    #  @likes = @record.likes.includes(:user)
  end

  def search
    @records = Record.search(params[:keyword])
  end

  def edit
    unless current_user == @record.user
      redirect_to root_path
    end
  end

  def update
    if current_user.id == @record.user_id && @record.update(record_params) 
    redirect_to record_path
    else 
      render:edit
    end
  end

  def destroy
    if current_user.id == @record.user_id && @record.destroy
    redirect_to root_path
    end
  end


  private
  def record_params
    params.require(:record).permit(:tr_theme, :tr_content, :category_id, :evaluation_id, :tr_day, :mvp, :mvp_reason, :image, :event).merge(user_id: current_user.id)
  end

  def set_record
    @record = Record.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @records = @user.records
    @users = @records.page(params[:page]).per(4)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>BuildUp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
  <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/records/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/records/new.css %>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('logo.png' , size: '120x120'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">練習記録の情報を入力</h2>
    <%= form_with(model: @record, local: true) do |f| %>

    <%= render 'shared/error_messages', model: f.object %>
    

    <%# 記録画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        思い出の1枚
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /記録画像 %>
    <%# テーマと説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        練習のテーマ
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :tr_theme, class:"items-text", id:"item-name", placeholder:"例）シュート練習（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          練習の内容・感想
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :tr_content, class:"items-text", id:"item-info", placeholder:"練習の説明（必須 1,000文字まで）（練習内容のポイント、感想など）例）シュート練習をしました。いろいろな種類のシュート練習をしたので、子ども達はとても楽しそうでした。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /テーマ名と説明 %>

    <%# 練習の詳細 %>
   <div class="items-detail">
      <div class="weight-bold-text">練習の詳細</div>
      <div class="form">
       <div class="weight-bold-text">
          練習日
          <span class="indispensable">必須</span>
        </div>
         <div class='input-birth-wrap'>
          <%= raw sprintf(
                  f.date_select(
                    :tr_day,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1990,
                    end_year: (Time.now.year),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
        <div class="weight-bold-text">
          スポーツの種目
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :event, class:"items-text", id:"item-name", placeholder:"種目名（必須 10文字まで)", maxlength:"10" %>
        <%# <%= f.collection_select(:hoge, [], :hoge, :hoge, {}, {class:"select-box", id:"item-category"}) %> 
        <div class="weight-bold-text">
          カテゴリー・学年
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id,Category.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /練習の詳細 %>

    <%# 振り返り %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>練習の振り返り</span>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          練習の評価
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:evaluation_id, Evaluation.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          練習のMVP
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :mvp, class:"items-text", id:"item-name", placeholder:"例)田中　太郎君", maxlength:"10" %>
        <div class="weight-bold-text">
          MVPの理由（一言で）
          <span class="indispensable">必須</span>
        </div>
       <%= f.text_area :mvp_reason, class:"items-text", id:"item-name", placeholder:"例)いつもより笑顔が多かった", maxlength:"40" %>
      </div>
    </div>
    
    
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', "#", class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">ビルドアップ利用規約</a></li>
    </ul>
    <%= link_to image_tag('logo.png' , size: '120x120'), "/" %>
    <p class="inc">
      ©︎Build.Up,Inc.
    </p>
  </footer>
</div>

app/views/records/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      選手と一緒に築き上げていく
    </h2>
    <p class='service-explain'>
      BuildUpは<br>
      スポーツを教えるコーチの<br>
      練習記録用アプリです<br>
      上手くいったことも<br>
      上手くいかなかったことも<br>
      すべての出来事は<br>
      選手を成長させてくれます<br>
      日々を練習記録して<br>
      振り返りながら<br>
      試行錯誤しながら<br>
      コーチも選手とともに<br>
      成長していきましょう<br>
      １日１日にの積み重ねが<br>
      選手の成長として<br>
      築き上げていかれるでしょう<br>
      さぁ、始めよう<br>
      BuildUp For Future Players
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
   
  </div>
  <%# /画面上部の帯部分  %>
   
  <%# 3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      BuildUpの3つの役割
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "osusume01.png", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>簡単に
          <span class='reason-list-blue-text'>記録できる</span>
          
        </h3>
        <p class='reason-list-description'>
          フォーマットに沿って入力するだけで簡単に練習内容や出来事を記録できる！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "osusume02.png", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
        いつでも
          <span class='reason-list-blue-text'>確認できる</span>
        
        </h3>
        <p class='reason-list-description'>
          記録を確認し、振り返ることで選手の成長を実感できる！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro03.png", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          記録を
          <span class='reason-list-blue-text'>シェア</span>
        </h3>
        <p class='reason-list-description'>
          記録を共有することで、指導者仲間の輪が広がる！
        </p>
      </li>
    </ul>
  </div>
  <%# 3つの理由部分 %>
<div class='ad-contents'>
    <h2 class='ad-title'>
      思い出の一枚を忘れずに
    </h2>
    <p class='ad-explain'>
      ただ、こなすだけの練習ではなく<br>
      一日一日の印象的なシーンを<br>
      写真も忘れずに投稿しましょう。<br>
      記録を見直したときに<br>
      昔の自分の感情を忘れないために。
    </p>
<div class='store-btn'>
      <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
      <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
    </div>
  </div>
  
  <%# 投稿一覧 %>
  <div class='item-contents'>
    <h2 class='title'>New Records</h2>
    <h3 class='subtitle'>新規投稿記録</h3>
    <ul class='item-lists'>
      <% @records.each do |record| %>
      <li class='list'>
        <%= link_to record_path(record.id) do %>
        <div class='item-img-content'>
          <%= image_tag record.image, class: "item-img" %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= record.tr_theme %>
          </h3>
          <div class='item-price'>
            <span><%= record.event %><br><%= record.user.nickname %></span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'><%= record.likes.count %></span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
      
       <% if @records[0] == nil %>
      <li class='list'>
        <%= link_to '#' do %>
        <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "item-img" %>
        <div class='item-info'>
          <h3 class='item-name'>
            記録を投稿してね！
          </h3>
          <div class='item-price'>
            <span>スポーツの種目名<br>投稿者</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
       <% end %> 
      </li>
    </ul>
    <%= paginate @records %>
  </div>
  
  <%# /投稿一覧 %>
</div>
<%= link_to(new_record_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>記録する</span>
  <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/records/search.html.erb
<%= render "shared/header" %>

<div class='item-contents'>
    <h2 class='title'>検索結果</h2>
    <ul class='item-lists'>
      <% @records.each do |record| %>
      <li class='list'>
        <%= link_to record_path(record.id) do %>
        <div class='item-img-content'>
          <%= image_tag record.image, class: "item-img" %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= record.tr_theme %>
          </h3>
          <div class='item-price'>
            <span><%= record.event %><br><%= record.user.nickname %></span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'><%= record.likes.count %></span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <% end %>
    </ul>
 </div>
<%= render "shared/footer" %>

app/views/records/show.html.erb
<%= render "shared/header" %>

<%# 記録の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
    <p>練習のテーマ</p>
      <%= "[#{@record.tr_theme}]" %>
    </h2>
    <div class='item-img-content'>
      <%= image_tag @record.image ,class:"item-box-img" %>
    </div>

 <% if user_signed_in? && current_user.id == @record.user_id  %>
    <%= link_to '練習記録の編集', edit_record_path(@record.id), method: :get, class: "item-red-btn" %>
    <p class='or-text'>or</p>
    <%= link_to '削除', record_path(@record.id), method: :delete, class:'item-destroy' %>
<% elsif user_signed_in? %>
    <%= link_to " #{@record.user.nickname}さんの投稿一覧", user_path(@record.user.id) ,class:"item-red-btn"%>   
 <% end %>

  

    <div class="item-explain-box">
     <div class="item-price-box">
    </div>
      
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">投稿者</th>
          <td class="detail-value"><%= @record.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">種目</th>
          <td class="detail-value"><%= @record.event %></td>
        </tr>
        <tr>
          <th class="detail-item">練習日</th>
          <td class="detail-value"><%= @record.tr_day %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @record.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">MVP</th>
          <td class="detail-value"><%= @record.mvp %></td>
        </tr>
        <tr>
          <th class="detail-item">MVPに選んだ理由</th>
          <td class="detail-value"><%= @record.mvp_reason %></td>
        </tr>
        <tr>
          <th class="detail-item">練習の評価</th>
          <td class="detail-value"><%= @record.evaluation.name %></td>
        </tr>
         <tr>
          <th class="detail-item">練習の内容や感想</th>
          <td class="detail-value"><%= @record.tr_content %></td>
        </tr>
        
      </tbody>
    </table>
    <% if user_signed_in?  %>
    <div class="option" >
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <p><span>お気に入り登録: </span><%=link_to @record.likes.count, record_likes_path(@record.id), method: :post %></p>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <p><span>お気に入り解除: </span><%=link_to @record.likes.count, record_likes_path(@record.id), method: :delete %></p>
      </div>
      <div class="count-btn">
        <p><span>お気に入りされた数: </span><%= @record.likes.count %></p>
      </div>
      <% else %>
       <div class="count-btn">
        <p><span>お気に入りされた数: </span><%= @record.likes.count %></p>
      </div>
        <p>※※※お気に入りやコメントをするにはユーザー登録をしましょう※※※</p>
      <% end %>
    </div>
  </div>
  <%# /記録の概要 %>
  <div class="comment-box">
     <% if user_signed_in? %>
        <%= form_with(model: [@record,@comment],local:true) do |f| %>
            <div class="comments">
              <%= f.label :text, "コメントをしよう" %><br />
              <%= f.text_field :text , rows: "2" %>
              <p class="comment-warn">
                相手のことを考え丁寧なコメントを心がけましょう。
              <br>
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
              </p>
            </div>
            <div class="actions">
               <%= f.submit "送信する", class: :comment_btn  %>
            </div>
         <% end %>
         <ul class="comments">
         <h3>＜コメント一覧＞</h3>
          <% if @comments %>
            <% @comments.each do |comment| %>
                <li class="comments">
                   <%= link_to comment.user.nickname, user_path(comment.user_id), class: :comment_user %>
                   <%= comment.text %><br>
                  <%= link_to 'コメントを削除する', record_comment_path(@record, comment), confirm: 'Are you sure?', method: :delete %>
               </li>
           </ul>
          <% end %>
        <% end %>  
    <% end%>
       
        
  </div>
  
  
</div>

<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    BuildUp For Future Players
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
    <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>BuildUpについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'BuildUp利用規約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>BuildUpを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>BuildUpについて</h2>
      <ul>
        <li><%= link_to 'BuildUpガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'BuildUpロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("logo.png", class:"logo-white"), "#" %>
  <p>© BuildUp</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("logo.png", class:"furima-icon"), "/" %>

    <%= form_with(url: search_records_path, local: true, method: :get, class:"search-form") do |f| %>
    <%= f.text_field :keyword, placeholder:'種目名から探す 例）サッカー',class:'input-box' %>
    <%= f.submit "検索", class:'search'%>
    <% end %>
  </div>
  <div class='nav'>
    <% if user_signed_in? %>
    <ul class='lists-right'>
      <li><%= link_to '新規投稿', new_record_path, class: "brand-list" %></li>
      <li><%= link_to "#{current_user.nickname}さんのマイページ", user_path(current_user.id), class: "user-nickname"%></li> 
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li> 
     <% else %>
    <ul class='lists-right'>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>BUILDUP利用規約</p>
  </div>
  <%= image_tag "logo.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("logo.png", class:"second-logo"), "/" %>
</header>